version: '3.8'

services:
  # Vector Database - Qdrant
  qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: liam-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - liam-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Main Application
  app:
    build: .
    container_name: liam-app
    ports:
      - "${PORT:-8081}:8081"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_URL=http://qdrant:6333
      - DATABASE_URL=${DATABASE_URL}
      - FLASK_ENV=production
      - PYTHONPATH=/app
    depends_on:
      qdrant:
        condition: service_healthy
    networks:
      - liam-network
    volumes:
      - ./sources:/app/sources:ro
    restart: unless-stopped

volumes:
  qdrant_data:
    driver: local

networks:
  liam-network:
    driver: bridge

